CREATE EXTENSION IF NOT EXIST "uuid-ossp";

CREATE TABLE IF NOT EXIST users (
    uid uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    name VARCHAR NOT NULL DEFAULT '',
    email VARCHAR NOT NULL UNIQUE,
    password VARCHAR NOT NULL,
    image_url VARCHAR NOT NULL DEFAULT '',
    website VARCHAR NOT NULL DEFAULT ''
);